[[redirects]]
from = "/*"
to = "index.html"
status = 200

[context.production.environment]
API_ENDPOINT = "https://production.yourservice.net"

[context.staging.environment]
API_ENDPOINT = "https://staging.yourservice.net"`

# no API server exists for other branches, but code will still want a URL here so need to set a "default"
[context.branch-deploy.environment]
API_ENDPOINT = "https://invalid"